#ifndef METROIDVANIASCENEONETILEMAP_H
#define METROIDVANIASCENEONETILEMAP_H

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * PixelRoot32 Exported Scene: MetroidvaniaSceneOneTileMap
 * Generated by PixelRoot32 Tilemap Editor
 */

namespace metroidvaniasceneonetilemap {

    // --- Tile Dimensions ---
    static const uint8_t TILE_SIZE = 8;
    static const uint8_t MAP_WIDTH = 30;
    static const uint8_t MAP_HEIGHT = 30;

    // --- Layer Definitions ---
    
    extern pixelroot32::graphics::TileMap4bpp background;
    
    extern pixelroot32::graphics::TileMap4bpp platforms;
    
    extern pixelroot32::graphics::TileMap4bpp stairs;
    

    /**
     * Initializes the scene components. 
     * Call this once before drawing in the render loop.
     */
    void init();

} // namespace metroidvaniasceneonetilemap

#endif // METROIDVANIASCENEONETILEMAP_H