// Generated by PixelRoot32 Sprite Compiler
// Engine: PixelRoot32
// Mode: 4bpp

// Palette (7 colors + transparent):
// Index 0: Transparent
// Index 1: RGB(31, 16, 42)
// Index 2: RGB(74, 48, 82)
// Index 3: RGB(201, 115, 115)
// Index 4: RGB(204, 66, 94)
// Index 5: RGB(234, 98, 98)
// Index 6: RGB(252, 239, 141)
// Index 7: RGB(255, 184, 121)

// Sprite 0 Dimensions: 8x8
static const uint16_t PLAYER_JUM_SPRITE_0_4BPP[] = {
    0x6000,
    0x0007,
    0x7600,
    0x0055,
    0x1700,
    0x0011,
    0x7400,
    0x0051,
    0x7230,
    0x0052,
    0x2003,
    0x0300,
    0x7500,
    0x0007,
    0x0500,
    0x0007,
};

// Sprite 1 Dimensions: 8x8
static const uint16_t PLAYER_JUM_SPRITE_1_4BPP[] = {
    0x0000,
    0x0000,
    0x7600,
    0x0000,
    0x5760,
    0x0005,
    0x1170,
    0x0001,
    0x1740,
    0x0005,
    0x2723,
    0x0005,
    0x7753,
    0x0003,
    0x7050,
    0x0000,
};

// Sprite 2 Dimensions: 8x8
static const uint16_t PLAYER_JUM_SPRITE_2_4BPP[] = {
    0x6000,
    0x0007,
    0x7600,
    0x0055,
    0x1700,
    0x0011,
    0x7430,
    0x0351,
    0x7230,
    0x0052,
    0x2000,
    0x0000,
    0x7500,
    0x0007,
    0x0050,
    0x0007,
};

// Sprite 3 Dimensions: 8x8
static const uint16_t PLAYER_JUM_SPRITE_3_4BPP[] = {
    0x0000,
    0x0076,
    0x6000,
    0x0557,
    0x7000,
    0x0111,
    0x4000,
    0x0517,
    0x2330,
    0x3527,
    0x0000,
    0x0002,
    0x5000,
    0x0077,
    0x0500,
    0x0070,
};

// Sprite 4 Dimensions: 8x8
static const uint16_t PLAYER_JUM_SPRITE_4_4BPP[] = {
    0x0000,
    0x0076,
    0x6000,
    0x0557,
    0x7000,
    0x0111,
    0x4000,
    0x0517,
    0x2300,
    0x0527,
    0x0030,
    0x3002,
    0x5000,
    0x0077,
    0x0500,
    0x0070,
};

