#ifndef PR32LOGO_H
#define PR32LOGO_H

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * PixelRoot32 Exported Scene: PR32Logo
 * Generated by PixelRoot32 Tilemap Editor
 */

namespace pr32logo {

    // --- Tile Dimensions ---
    static const uint8_t TILE_SIZE = 16;
    static const uint8_t MAP_WIDTH = 20;
    static const uint8_t MAP_HEIGHT = 15;

    // --- Layer Definitions ---
    
    extern pixelroot32::graphics::TileMap4bpp background;
    

    /**
     * Initializes the scene components. 
     * Call this once before drawing in the render loop.
     */
    void init();

} // namespace pr32logo

#endif // PR32LOGO_H