#ifndef BACKGROUND_ASSETS_H
#define BACKGROUND_ASSETS_H

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * PixelRoot32 Exported Scene: Background Assets
 * Generated by PixelRoot32 Tilemap Editor
 */

namespace background_assets {

    // --- Tile Dimensions ---
    static const uint8_t TILE_SIZE = 8;
    static const uint8_t MAP_WIDTH = 40;
    static const uint8_t MAP_HEIGHT = 30;

    // --- Layer Definitions ---
    
    extern pixelroot32::graphics::TileMap background;
    

    /**
     * Initializes the scene components. 
     * Call this once before drawing in the render loop.
     */
    void init();

} // namespace scene_1

#endif // BACKGROUND_ASSETS_H